name: Prettier

on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        working-directory: ./client
        with:
          node-version: 16

      - run: yarn install
      - run: yarn prettier-check
